[package]
name = "lithium"
version = "0.1.0"
edition = "2024"
description = "A logger wrapper with elapsed time tracking and colorized output built on env_logger, log"
license = "MIT"
readme = "README.md"
repository = "https://github.com/cerclique/lithium"
publish = false

[dependencies]
env_logger = { version = "0.11.11", features = ["default"] }
log = "0.4.33"
thiserror = "2.0.19"

[[example]]
name = "main"
path = "examples/main.rs"
